import {defineField, defineType} from 'sanity'

export const workflowTransition = defineType({
  name: 'workflowTransition',
  title: 'Workflow transition',
  type: 'document',
  fields: [
    defineField({
      name: 'sourceAction',
      title: 'Source action',
      type: 'reference',
      to: [{type: 'temporalAction'}],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'transitionState',
      title: 'Transition state',
      type: 'string',
      options: {
        list: [
          {title: 'Past action committed', value: 'PAST_ACTION_COMMITTED'},
          {title: 'Future state recalculation', value: 'FUTURE_STATE_RECALCULATION'},
          {title: 'Game Master review', value: 'GAME_MASTER_REVIEW'},
          {title: 'Timeline sealed', value: 'TIMELINE_SEALED'},
        ],
      },
      initialValue: 'PAST_ACTION_COMMITTED',
    }),
    defineField({
      name: 'agentAnalysis',
      title: 'Agent analysis',
      type: 'text',
      description: "Notes generated by the causality agent explaining its reasoning",
    }),
    defineField({
      name: 'calculatedChanges',
      title: 'Calculated changes',
      type: 'array',
      description: 'A snapshot of what the agent decided to change',
      of: [
        {
          type: 'object',
          name: 'calculatedChange',
          fields: [
            defineField({
              name: 'targetDocument',
              title: 'Target document',
              type: 'reference',
              to: [{type: 'room'}, {type: 'gameObject'}, {type: 'clue'}],
            }),
            defineField({name: 'changeSummary', title: 'Change summary', type: 'string'}),
          ],
        },
      ],
    }),
    defineField({
      name: 'paradoxFlags',
      title: 'Paradox flags',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'paradox'}]}],
    }),
    defineField({
      name: 'gmApproval',
      title: 'Game Master approval',
      type: 'object',
      fields: [
        defineField({name: 'approved', title: 'Approved', type: 'boolean', initialValue: false}),
        defineField({name: 'approvedAt', title: 'Approved at', type: 'datetime'}),
      ],
    }),
    defineField({
      name: 'finalSealedState',
      title: 'Final sealed state',
      type: 'boolean',
      initialValue: false,
    }),
  ],
  preview: {
    select: {title: 'transitionState', subtitle: 'sourceAction.description'},
  },
})
